spring:
  application:
    name: spaGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: spaMovie
          uri: lb://spaMovie
          predicates:
            - Path=/movies/{id}
        - id: movie
          uri: lb://movie
          predicates:
            - Path=/movies/**
server:
  port: 9090