spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: movie-sc-route
          uri: lb://movie
          predicates:
            - Path=/movies/**
        - id: comment-sc-route
          uri: lb://comment
          predicates:
            - Path=/comments/**
        - id: auth-sc-route
          uri: lb://auth
          predicates:
            - Path=/login, /signup
      discovery:
        locator:
          enabled: true