server:
  port: 8085
  servlet:
    context-path: /auth
mflix:
  apis:
    movie:
      url: http://localhost:8081
    comment:
      url: http://localhost:8083
    stream:
      url: http://localhost:8082
    user:
      url: http://localhost:8084
    auth:
      url: http://localhost:8085