spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: spaGateway
          uri: lb://spaGateway
          predicates:
            - Path=/**
      discovery:
        locator:
          enabled: true